### ISSUE TITLE
create phonologizer for French corpora

### ISSUE THREAD

**Issue by alecristia** [alecristia/CDSwordSeg#1]

**Comment by mmmaat** [comment]
Is espeak can be a suitable phonemizer for French ?

```
$ espeak --ipa -vfr "Je phonemise le français directement en IPA"
ʒə- fɔnmˈiz lə- fʁɑ̃sˈɛ diʁɛktəmˈɑ̃ ɑ̃n ˌipˌeˈa
```

An alternative can be LIA_PHON (http://tcts.fpms.ac.be/synthesis/mbrola/tts/French/lia_phon.tar.gz)

**Comment by alecristia** [comment]
​looks perfect!!

**Comment by mmmaat** [comment]
I'll work on that next Monday. If you are agree I plan to update the https://github.com/bootphon/phonemizer package with espeak support of new languages. So I'll not modify any code in CDS, (or just at the margin to support the integration with the phonemizer...)

You'll have **French, Spanish, Catalan and many many others** for free (see section 3.4 of http://espeak.sourceforge.net/languages.html).

Does it sound good?

**Comment by mmmaat** [comment]
I just updated the phonemizer with espeak support, have a look to https://github.com/bootphon/phonemizer
