### ISSUE TITLE
wrong number of iteration in bash files for adaptor grammar?

### ISSUE THREAD

**Issue by alecristia** [alecristia/CDSwordSeg#2]
# number of iterations per parse, normally 2000 (except for
# debugging-10)
NITER=10

should be 2k -- is this parameter passed otherwise & in fact this file not used at all?

**Comment by mmmaat** [comment]
In segment.py you have the --ag-debug option that setups AG with debug params (NITER=10), if not specified the program uses NITER=2k

**Comment by alecristia** [comment]
let me see if I get it straight, taking the bernstein as a case:
1) 3_analyze calls segment.py
2) segment.py at the top level within algocomp calls AG.sh passing one of
two args AGu or AGC3sf
3) AG.sh calls algos/AG/do_AG_english.sh and passes that arg, and the debug
call
4) and do_AG_english.sh calls e.g. for AGu
GRAMMARFILE=$ABSPATH/grammars/Colloc0_enFestival.lt

I think I got it now. What confused me is that there is also:
do_coll3syll_english.sh
do_colloq0_english.sh
in the same folder as do_AG_english.sh

so I'll remove them and update the readme.
​
