### ISSUE TITLE
errors when running any algo on Spanish corpora

### ISSUE THREAD

**Issue by alecristia** [alecristia/CDSwordSeg#4]
sh: error importing function definition for `BASH_FUNC_module()'
/bin/sh: error importing function definition for `BASH_FUNC_module()'
-catch_rsh /cm/local/apps/sge/var/spool/puck2/active_jobs/563390.1/pe_hostfile
puck2
puck2
puck2
puck2
puck2
puck2
puck2
puck2
Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
bash: error importing function definition for `BASH_FUNC_module()'

Shall I add some markers to find exactly where the problem emerges from, or does this sound like something you've seen before?

**Comment by elinlarsen** [comment]
I've never seen this before ...

**Comment by mmmaat** [comment]
This is related to jobs submission on the cluster with Sun Grid Engine. I've already seen this in other contexts. This is usually not an error, just a warning you can ignore.

The result is not impacted I guess?
How did you launch the job ? qsub, segment.py ?

**Comment by alecristia** [comment]
Yes! Dibs tps and puddle worked straight away, and after some false stays
we have correctly adapted agu. So all that we need is working, thanks!
Il 02/Dic/2016 11:44 "Mathieu Bernard" <notifications@github.com> ha
scritto:
